### ISSUE TITLE
72 character limit?

### ISSUE THREAD

**Issue by JohnMcW** [fpirsch/twin-bcrypt#10]
Hi,

Why is this code generating identical hashes?  It seems like it ignores anything beyond 72 characters.

```
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/twin-bcrypt@2.1.1/twin-bcrypt.min.js"></script>
<script>
var string1 = "Lorem ipsum dolor sit amet, vix eu consequat contentiones. Cu salutandi "
var string2 = "Lorem ipsum dolor sit amet, vix eu consequat contentiones. Cu salutandi accusamus incorrupte eos. Dicta graeci minimum mel ne. Te probo consul splendide his, omnis dolorem eos ex. Vel ut animal fabellas, cu cum iudico saperet. Est vivendo conceptam signiferumque ex, nam at wisi rebum."
hash1 = TwinBcrypt.hashSync(string1, "$2y$10$kJuyLKJVZ5K0OOaaqftTb.");
console.log(hash1);
hash2 = TwinBcrypt.hashSync(string2, "$2y$10$kJuyLKJVZ5K0OOaaqftTb.");
console.log(hash2);
</script>
</head>
</html>
```
I was using Chrome, but just tried in Firefox, and its console showed more detail:

```
TypeError: asm.js link error: ArrayBuffer byteLength 0x2000 is not a valid heap length. The next valid length is 0x10000 twin-bcrypt.min.js:6:1244
TypeError: asm.js type error: Disabled by 'asmjs' runtime option twin-bcrypt.min.js
```
No idea if its related though.
Thanks!

**Comment by JohnMcW** [comment]
OK - so I just found out that this is a limit with bcrypt in general, so I'll close this.  If you're interested, I'm using twin-bcrypt here for a couple of use cases: http://www.cryptoquiz.cafe/ - it's pretty self explanatory - but I'll need to swap it out for probably SHA256 for the second use case.  Thanks!

**Comment by fpirsch** [comment]
Hi John !
Actually the limit is 72 **bytes** not characters. Thanks for pointing it, I updated the `README.md`.
