### ISSUE TITLE
Usage example with salt gen?

### ISSUE THREAD

**Issue by nelsonic** [fpirsch/twin-bcrypt#3]
Would this work:
```js
var twinbcrypt = require('twin-bcrypt');
var bcrypt       = require('bcrypt');
var assert       = require('assert');

var salt  = twinbcrypt.genSalt(12);
var hash = twinbcrypt.hashSync('hello', salt);

assert.equal(bcrypt.compareSync("hello", hash) === true, "twin-bcrypt is compatible with bcrypt");
```

> ***fails*** ... what am I doing wrong...? (*thanks*!)

**Comment by adrianblynch** [comment]
I see the same.

Comparing to a `bcryptjs` derived hash works. Not so for `bcrypt`.

**Comment by fpirsch** [comment]
Twin-Bcrypt generates `$2y$` hashes. Is the other bcrypt lib able to handle `$2y$` ?

**Comment by fpirsch** [comment]
@nelsonic I assume you are referring to [node.bcrypt.js](https://github.com/ncb000gt/node.bcrypt.js) which doesn't seem to handle the `2y` prefix.
FYI, Twin-Bcrypt passes the GNU Openwall bcrypt test suite.

**Comment by nelsonic** [comment]
Thanks for confirming that @fpirsch :+1:
