### ISSUE TITLE
MIT license instead of BSD 3-clause

### ISSUE THREAD

**Issue by tresdin** [fpirsch/twin-bcrypt#5]
My application automatically merges all files into 1 large minified file that unintentionally eliminates the license notice. And adding this notice is not an easy stuff to me. I really appreciate if you change your license to MIT.

**Comment by fpirsch** [comment]
You can preserve license-related comments during minification.
I just added the `@license` tag for this to work, in v2.1.2
UglifyJS will preserve comments containing this tag if you run it with the `--comments` option. This should work with Google Closure Compiler too.
BSD-3-clause and MIT are compatible, both can coexist in the same packaged file.
