### ISSUE TITLE
setImmediate is not defined on browser context

### ISSUE THREAD

**Issue by tresdin** [fpirsch/twin-bcrypt#6]
I tried asynchronously hashing a simple password.
```
TwinBcrypt.hash('12345678',function(hash){
     console.log(hash);
});
```
Instead of the hash, I got this error while executing the above code within a dedicated worker.
```
Uncaught ReferenceError: setImmediate is not defined
```

*Side note: I'm using Chrome 43 Beta*

**Comment by fpirsch** [comment]
The `setImmediate` polyfill is bundled with the minified version of twin-bcrypt. But it might suffer from the global scope issue #4 in web workers + strict mode. I'll be looking into this.

**Comment by tresdin** [comment]
You've showed me the point. I'm using the non-minified version. :)
I think it will be better if you include the polyfill in both versions.
