### ISSUE TITLE
Error convention in asynchronous methods

### ISSUE THREAD

**Issue by tresdin** [fpirsch/twin-bcrypt#7]
Since first argument of an asynchronous method in nodejs is always an error or a null value, I really think that `twin-bcrypt` should follow this convention.
```
TwinBcrypt.hash("bacon", function(er,hash) {
  console.log(er,hash);
});
TwinBcrypt.compare("bacon", hash, function(er,result) {
    console.log(er,result);
})

**Comment by fpirsch** [comment]
I generally agree it is best to follow conventions. However in this case it makes no sense, since `er` would always be null. The only errors in this lib are synchronous by nature.
Plus, this library is not Node-only, and the `(err, result)` convention does not exist in browsers.
I would rather use Promises.
[io](https://iojs.org) has them out of the box, hopefully node will follow ;-)

**Comment by tresdin** [comment]
IMHO, you should wrap the code inside a `try catch` block instead of throwing it in synchronous style.
Promise can be good for the case of the event emitters, but the simple in and out asynchronous operations.

**Comment by fpirsch** [comment]
But there is nothing to `try catch` since the algorithm itself never produces errors. The only possible error is bad parameters (e.g. no callback given...)

**Comment by julien-f** [comment]
@fpirsch You can start using promise right now (for instance using [native-or-bluebird](https://github.com/normalize/native-or-bluebird).

The problem in not using the convention for the callback is that it makes this library not promisifiable with current helpers such as `Bluebird.promisify()`.

**Comment by fpirsch** [comment]
Promises still leave the progress notification problem open. Anyway, it's still possible to promisify this library quite simply:
```
var promisedHash = function(data, salt, progress) {
  return new Promise(function(resolve) {
    TwinBcrypt.hash(data, salt, progress, resolve);
  }
};

var promisedCompare = function(password, refhash, progress) {
  return new Promise(function(resolve) {
    TwinBcrypt.compare(password, refhash, progress, resolve);
  }
};
```

Usage:
```
promisedHash('my password').then(function(hash) {
  console.log('hash is ' + hash);
});
```

**Comment by tresdin** [comment]
@fpirsch Throwing an error in asynchronous operations is never gonna be a good idea in node. Because this behaviour will take a worker down. And wrapping async methods in try catch block is not really nice, right?
